### ISSUE TITLE
[offtopic] Transfer of django-fsm-admin ownership

### ISSUE THREAD

**Issue by bashu** [gadventures/gapipy#127]
Hi,

This repository  gadventures /
django-fsm-admin  seems to lack maintenance, I propose myself as a new maintainer.

Could you give me the right to push in your repository or just transfer it on my account in github?

Thank you!

PS: We still use it some legacy projects and I am willing to keep it maintained.

PPS: If you are not sure about me, for example I maintain (or helping):

https://github.com/shanx/django-maintenancemode

https://github.com/adamcharnock/django-tz-detect

Also I adopted few Django projects and still continue maintaining them, biggest example:

https://github.com/bashu/django-easy-maps

PPPS: I've tried to reach you via contact form on https://www.gadventures.com/

**Comment by bashu** [comment]
cc @jonprindiville @marz619 can you please look at this? Thanks in advance!

**Comment by marz619** [comment]
Hi @bashu we are looking into this internally, and will continue the topic at https://github.com/gadventures/django-fsm-admin/issues/84
