### ISSUE TITLE
`get`-ing a resource that was cached in `RedisCache` refreshes that key's TTL

### ISSUE THREAD

**Issue by jonprindiville** [gadventures/gapipy#65]
Steps to reproduce:

- instantiate a gapipy using `gapipy.cache.RedisCache` as cache backend and some default TTL, e.g. `'cache_options': { 'default_timeout': 60*60 }`
- fetch a resource so that it is inserted into Redis, e.g. `gapipy_instance.itineraries.get(1198, 946, cached=False)`
- check the TTL of that key (e.g. `redis-cli ttl '*itineraries:1198:946*'`) -- it will be the default timeout you set minus the few seconds that have passed since calling `get`
- wait a few seconds
- fetch the same resource again but tell gapipy to use its cache, e.g. `gapipy_instance.itineraries.get(1198, 946, cached=True)`
- check the TTL of that key again, the default timeout you set minus the few seconds that have passed since your most recent call to `get`

Expected behaviour:
- subsequent gets that are served from cache should not disturb the TTL of the key, in the above example, our second check of the TTL should be lower than the first check

Effect:
- a resource cached in Redis that is fetched from cache more than once-per-TTL will never fall out of the cache

**Comment by marz619** [comment]
https://github.com/gadventures/gapipy/blob/master/gapipy/query.py#L70 is the offending line of code. It gets called irregardless of where the data was retrieved.

1. We could modify the return signature of `get_resource_data` to include a second Boolean that signifies if the resource was retrieved via the cache or from G-API.

2. Use the `is_cached` functionality  prior to calling the `set` method to push the resource into the `cache`

**Comment by jonprindiville** [comment]
Yeah -- another option without changing an signatures would be move that `set` call into `get_resource_data` (where we are aware if we hit the cache or not)

---

I'm thinking about whether or not we can write tests around this -- I guess we'd need a Redis (or very extensive mocking... which I feel "meh" about) in our test environments 🤔

**Comment by jonprindiville** [comment]
Fix merged into `master`, thanks! Closing this issue.

(Still needs a release + version number, though cc @bartek)
