### ISSUE TITLE
Sticky `filter` arguments

### ISSUE THREAD

**Issue by jonprindiville** [gadventures/gapipy#76]
I'm seeing some confusing behaviour... let talk about whether it's a bug or not!

## Repro steps:

0. Hop into a shell and instantiate yourself a gapipy client, I'll call it `g` in this example...

1. Search for departures having a certain tour dossier associated with them... found some! Then search for departures having a certain itinerary associated with them... none found.

```
    >>> len([x for x in g.departures.filter(**{'tour_dossier.id': '22758'}).all()])
    280

    >>> len([x for x in g.departures.filter(**{'structured_itineraries.variation_id': 4364}).all()])
    0
```

2. Ok, kill that shell. Start a fresh shell and we'll swap the order... search for the itinerary association first and it returns results! Search for the tour_dossier association second and it returns no results. The opposite of last time.

```
    >>> len([x for x in g.departures.filter(**{'structured_itineraries.variation_id': 4364}).all()])
    91

    >>> len([x for x in g.departures.filter(**{'tour_dossier.id': '22758'}).all()])
    0
```

3. 🤔 

## Expected result:

Order of operations shouldn't matter. We should see 280 departures for `tour_dossier.id=22758` and 91 for `structured_itineraries.variation_id=4364`.

## Investigation:

Looking at the `Query` class, it seems as though we clear `self._filters` after making _some_ requests, but not all:

- `get_resource_data` [resets it](https://github.com/gadventures/gapipy/blob/e91484bd2f99684d701bad54da5285104aeecad3/gapipy/query.py#L89) after doing `APIRequestor.get` (and caching the result)
- `count` [resets it](https://github.com/gadventures/gapipy/blob/e91484bd2f99684d701bad54da5285104aeecad3/gapipy/query.py#L165) after doing `APIRequestor.list_raw` (and extracting the count)
- `all` [calls `APIRequestor.list` but doesn't reset `self._filters`](https://github.com/gadventures/gapipy/blob/e91484bd2f99684d701bad54da5285104aeecad3/gapipy/query.py#L121-L141)

## Thoughts:

In _my_ opinion `Query.all` should reset `self._filters` after it calls `APIRequestor.list` and makes its request to the API -- adopting the same behaviour as the other two `Query` code paths which hit the API.

On the other hand, there is [a test case that _highlights_ the fact that we can "chain" filters in this way](https://github.com/gadventures/gapipy/blob/e91484bd2f99684d701bad54da5285104aeecad3/tests/test_query.py#L162).

This seems like an odd pair of behaviours to have (again, IMO):

- if I `.count()` my query the filters are reset
- if I `.all()` or `list(...)` my query the filters are not reset

---

NB: my contrived example could avoid this behaviour and obtain correct counts using `Query.count` rather than iterating over the list... it's easy to imagine similar analogous situations where e.g. whole resources and not counts are required

**Comment by bartek** [comment]
@jonprindiville Was this issue solved by the PR or is there more to it?

**Comment by jonprindiville** [comment]
Oh yeah, IMO this is resolved. Just forgot about closing this issue.
